# Generated by Django 5.2.5 on 2025-08-18 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actives',
            name='fixed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда звонил'),
        ),
        migrations.AddField(
            model_name='actives',
            name='fixed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls_made', to=settings.AUTH_USER_MODEL, verbose_name='Кто звонил'),
        ),
        migrations.AddIndex(
            model_name='actives',
            index=models.Index(fields=['fixed_at'], name='crm_api_act_fixed_a_a4dd49_idx'),
        ),
        migrations.AddIndex(
            model_name='actives',
            index=models.Index(fields=['fixed_by'], name='crm_api_act_fixed_b_5736c5_idx'),
        ),
    ]
