# Generated by Django 5.2.5 on 2025-08-18 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0002_actives_fixed_at_actives_fixed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d')),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('processed', 'processed'), ('failed', 'failed')], db_index=True, default='new', max_length=16)),
                ('rows_found', models.PositiveIntegerField(default=0)),
                ('rows_saved', models.PositiveIntegerField(default=0)),
                ('log', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
                'indexes': [models.Index(fields=['uploaded_at'], name='crm_api_exc_uploade_2b7eeb_idx'), models.Index(fields=['status'], name='crm_api_exc_status_0922f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SbmsAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=250)),
                ('old_client', models.CharField(blank=True, default='', max_length=300)),
                ('new_client', models.CharField(blank=True, default='', max_length=300)),
                ('old_status', models.CharField(blank=True, default='', max_length=150)),
                ('new_status', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.TextField(blank=True, default='')),
                ('ok', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('abonent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sbms_audit', to='crm_api.actives')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='crm_api_sbm_created_d60391_idx'), models.Index(fields=['msisdn'], name='crm_api_sbm_msisdn_edcdb9_idx'), models.Index(fields=['ok'], name='crm_api_sbm_ok_c71185_idx')],
            },
        ),
    ]
