# Generated by Django 5.2.5 on 2025-08-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0003_excelupload_sbmsaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='excelupload',
            index=models.Index(fields=['uploaded_by'], name='crm_api_exc_uploade_b1a0dc_idx'),
        ),
    ]
