# Generated by Django 5.2.5 on 2025-08-19 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0004_alter_excelupload_original_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('google_email', models.CharField(blank=True, default='', max_length=255)),
                ('user_data_dir', models.CharField(help_text='Путь к папке профиля Chrome', max_length=500, unique=True)),
                ('profile_directory', models.CharField(default='Default', help_text='Имя профиля внутри user-data-dir', max_length=100)),
                ('chrome_binary', models.CharField(blank=True, default='', help_text='Путь к chrome, если нестандартный', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Google account (Chrome profile)',
                'verbose_name_plural': 'Google accounts (Chrome profiles)',
            },
        ),
        migrations.CreateModel(
            name='SBMSAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('max_google_accounts', models.PositiveSmallIntegerField(default=5, help_text='Ожидаемое число привязанных Google-аккаунтов')),
            ],
            options={
                'verbose_name': 'SBMS account',
                'verbose_name_plural': 'SBMS accounts',
            },
        ),
        migrations.RemoveIndex(
            model_name='excelupload',
            name='crm_api_exc_uploade_b1a0dc_idx',
        ),
        migrations.AddField(
            model_name='excelupload',
            name='batch_tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='original_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='excelupload',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('processed', 'processed'), ('failed', 'failed')], db_index=True, default='new', max_length=16),
        ),
        migrations.AddField(
            model_name='excelupload',
            name='google_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='crm_api.googleaccount'),
        ),
        migrations.AddIndex(
            model_name='excelupload',
            index=models.Index(fields=['batch_tag'], name='crm_api_exc_batch_t_38f811_idx'),
        ),
        migrations.AddIndex(
            model_name='excelupload',
            index=models.Index(fields=['google_account'], name='crm_api_exc_google__2ed995_idx'),
        ),
        migrations.AddIndex(
            model_name='sbmsaccount',
            index=models.Index(fields=['is_active'], name='crm_api_sbm_is_acti_cad77c_idx'),
        ),
        migrations.AddIndex(
            model_name='sbmsaccount',
            index=models.Index(fields=['username'], name='crm_api_sbm_usernam_5f4113_idx'),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='sbms_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='google_accounts', to='crm_api.sbmsaccount'),
        ),
        migrations.AddIndex(
            model_name='googleaccount',
            index=models.Index(fields=['is_active'], name='crm_api_goo_is_acti_a9d56a_idx'),
        ),
        migrations.AddIndex(
            model_name='googleaccount',
            index=models.Index(fields=['sbms_account'], name='crm_api_goo_sbms_ac_c97523_idx'),
        ),
    ]
