# Generated by Django 5.2.5 on 2025-08-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0005_googleaccount_sbmsaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleaccount',
            name='profile_directory',
            field=models.CharField(blank=True, default='Default', help_text='Имя профиля внутри user-data-dir', max_length=100, null=True),
        ),
    ]
