# Generated by Django 5.2.5 on 2025-08-19 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0006_alter_googleaccount_profile_directory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='excelupload',
            name='crm_api_exc_google__2ed995_idx',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='google_account',
        ),
    ]
