# Generated by Django 5.2.5 on 2025-08-20 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0007_remove_excelupload_crm_api_exc_google__2ed995_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(db_index=True, max_length=20)),
                ('logger', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField()),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('pathname', models.CharField(blank=True, default='', max_length=500)),
                ('func_name', models.CharField(blank=True, default='', max_length=200)),
                ('lineno', models.IntegerField(default=0)),
                ('exc_text', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='crm_api_log_created_862a58_idx'), models.Index(fields=['level'], name='crm_api_log_level_31c9c3_idx'), models.Index(fields=['logger'], name='crm_api_log_logger_e7943e_idx'), models.Index(fields=['request_id'], name='crm_api_log_request_8ad997_idx'), models.Index(fields=['user'], name='crm_api_log_user_id_556d8e_idx')],
            },
        ),
    ]
