# Generated by Django 5.2.5 on 2025-08-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0008_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelupload',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to='runlogs/%Y/%m/%d'),
        ),
    ]
