# Generated by Django 5.2.5 on 2025-08-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0009_excelupload_log_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
