# Generated by Django 5.2.5 on 2025-08-20 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0010_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspendMeta',
            fields=[
                ('abonent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='suspend_meta', serialize=False, to='crm_api.actives')),
                ('last_recheck_log_path', models.CharField(blank=True, default='', max_length=512)),
                ('last_recheck_activated_path', models.CharField(blank=True, default='', max_length=512)),
                ('last_recheck_at', models.DateTimeField(blank=True, null=True)),
                ('last_recheck_run_id', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'verbose_name': 'Suspend meta',
                'verbose_name_plural': 'Suspends meta',
            },
        ),
    ]
