# Generated by Django 5.2.5 on 2025-08-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0011_suspendmeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('checked', models.IntegerField(default=0)),
                ('activated', models.IntegerField(default=0)),
                ('still_suspend', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('log_path', models.CharField(blank=True, default='', max_length=512)),
                ('activated_path', models.CharField(blank=True, default='', max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='SuspendMeta',
        ),
    ]
