# Generated by Django 5.2.5 on 2025-08-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0012_recheckrun_delete_suspendmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='recheckrun',
            name='log_file',
            field=models.FileField(blank=True, null=True, upload_to='runlogs/%Y/%m/%d'),
        ),
    ]
