# Generated by Django 5.2.5 on 2025-08-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0016_uploadjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excelupload',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='excelupload',
            name='crm_api_exc_uploade_2b7eeb_idx',
        ),
        migrations.RemoveIndex(
            model_name='excelupload',
            name='crm_api_exc_status_0922f6_idx',
        ),
        migrations.RemoveIndex(
            model_name='excelupload',
            name='crm_api_exc_batch_t_38f811_idx',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='batch_tag',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='log',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='log_file',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='rows_found',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='rows_saved',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='status',
        ),
        migrations.RemoveField(
            model_name='excelupload',
            name='uploaded_by',
        ),
    ]
