# Generated by Django 5.2.5 on 2025-08-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0017_alter_excelupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actives',
            name='account',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='actives',
            name='msisdn',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='actives',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='user_data_dir',
            field=models.CharField(help_text='Путь к папке профиля Chrome', max_length=500),
        ),
        migrations.AlterField(
            model_name='recheckrun',
            name='run_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sbmsaccount',
            name='label',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sbmsaccount',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
