# Generated by Django 5.2.5 on 2025-09-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0018_alter_actives_account_alter_actives_msisdn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleaccount',
            name='sbms_account',
        ),
        migrations.DeleteModel(
            name='RecheckRun',
        ),
        migrations.RemoveField(
            model_name='sbmsaudit',
            name='abonent',
        ),
        migrations.AlterModelOptions(
            name='actives',
            options={'verbose_name': 'Active', 'verbose_name_plural': 'Actives'},
        ),
        migrations.DeleteModel(
            name='GoogleAccount',
        ),
        migrations.DeleteModel(
            name='SBMSAccount',
        ),
        migrations.DeleteModel(
            name='SbmsAudit',
        ),
    ]
