# Generated by Django 5.2.5 on 2025-09-01 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0019_remove_googleaccount_sbms_account_delete_recheckrun_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(blank=True, max_length=250, null=True)),
                ('departments', models.CharField(blank=True, max_length=300, null=True)),
                ('status_from', models.CharField(blank=True, max_length=100, null=True)),
                ('days_in_status', models.PositiveIntegerField(default=0)),
                ('write_offs_date', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.CharField(blank=True, max_length=300, null=True)),
                ('rate_plan', models.CharField(blank=True, max_length=200, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('subscription_fee', models.IntegerField(default=0)),
                ('account', models.CharField(blank=True, max_length=32, null=True)),
                ('branches', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('status_call', models.CharField(blank=True, choices=[('Дозвонился', 'Дозвонился'), ('Не дозвонился', 'Не дозвонился'), ('Не звонили', 'Не звонили')], max_length=20, null=True)),
                ('call_result', models.CharField(blank=True, choices=[('Нет ответа', 'Нет ответа'), ('Ответили на вопрос', 'Ответили на вопрос'), ('Отказ от разговора', 'Отказ от разговора'), ('Другой владелец номера', 'Другой владелец номера'), ('Нет ответа', 'Нет ответа'), ('Аппарат выкл', 'Аппарат выкл'), ('Номер не существует', 'Номер не существует'), ('Дубликат номера', 'Дубликат номера'), ('Статус активный', 'Статус активный')], max_length=32, null=True)),
                ('abonent_answer', models.CharField(blank=True, choices=[('Нет ответа', 'Нет ответа'), ('Временно нет потребности в интернете', 'Временно нет потребности в интернете'), ('Финансовые трудности', 'Финансовые трудности'), ('Забыли внести платеж', 'Забыли внести платеж'), ('Высокая стоимость ТП', 'Высокая стоимость ТП'), ('Не устраивает качество сети', 'Не устраивает качество сети'), ('Плохое обслуживание', 'Плохое обслуживание'), ('Переезд', 'Переезд'), ('Смена технологии', 'Смена технологии'), ('Смена провайдера', 'Смена провайдера'), ('Абонент активный', 'Абонент активный'), ('Оплатит в скором времени', 'Оплатит в скором времени'), ('Другой', 'Другой')], max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('tech', models.CharField(blank=True, choices=[('pon', 'pon'), ('vdsl', 'vdsl'), ('adsl', 'adsl'), ('ethernet', 'ethernet')], max_length=16, null=True)),
                ('fixed_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда звонил')),
                ('moved_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fixed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_calls_moved', to=settings.AUTH_USER_MODEL, verbose_name='Кто звонил')),
            ],
            options={
                'verbose_name': 'Fixed',
                'verbose_name_plural': 'Fixeds',
                'indexes': [models.Index(fields=['msisdn'], name='crm_api_fix_msisdn_f9ac0b_idx'), models.Index(fields=['phone'], name='crm_api_fix_phone_b4b967_idx'), models.Index(fields=['branches'], name='crm_api_fix_branche_431812_idx'), models.Index(fields=['rate_plan'], name='crm_api_fix_rate_pl_31ca1b_idx'), models.Index(fields=['status'], name='crm_api_fix_status_bd267b_idx'), models.Index(fields=['status_call'], name='crm_api_fix_status__7978d0_idx'), models.Index(fields=['call_result'], name='crm_api_fix_call_re_dabbfd_idx'), models.Index(fields=['abonent_answer'], name='crm_api_fix_abonent_938492_idx'), models.Index(fields=['tech'], name='crm_api_fix_tech_b5270c_idx'), models.Index(fields=['fixed_at'], name='crm_api_fix_fixed_a_ed12ac_idx'), models.Index(fields=['fixed_by'], name='crm_api_fix_fixed_b_fa38fa_idx'), models.Index(fields=['moved_at'], name='crm_api_fix_moved_a_16aa25_idx')],
            },
        ),
    ]
