# Generated by Django 5.2.5 on 2025-09-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0020_fixeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixeds',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeds',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fixeds',
            index=models.Index(fields=['created_at'], name='crm_api_fix_created_8801cb_idx'),
        ),
        migrations.AddIndex(
            model_name='fixeds',
            index=models.Index(fields=['updated_at'], name='crm_api_fix_updated_67522b_idx'),
        ),
    ]
