# Generated by Django 5.2.5 on 2025-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0021_fixeds_created_at_fixeds_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actives',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixeds',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
